### PR TITLE
NetBox v2 API client generated using OpenAPI

### PR DESCRIPTION
**Pull request by davcamer**
Used go-swagger with a swagger generated from a local build of NetBox
that is using drf-yasg with custom modifications to generate a complete
swagger.json.

### CODE REVIEW

**Comment by davcamer** [comment]
Addresses #26. 

Travis is certainly broken. Given that all the code is generated, I'm less sure how to approach the travis build.

**Comment by mdlayher** [comment]
This is interesting but I honestly don't even know where to begin reviewing or using it.

Do you have any code examples that show this in action?

**Comment by davcamer** [comment]
I have a small example from an internal project:
```go
package netbox

import (
	"context"
	"time"

	"github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/digitalocean/go-netbox"
)

type netboxRepository struct {
	client *netbox.NetBox
}

var _ models.NetboxRepository = netboxRepository{}

func New(host string, basepath string, timeout time.Duration) (models.NetboxRepository) {
	httpsClient, err := client.TLSClient(client.TLSClientOptions{
		ServerName: "my.netbox.server",
	})
	if err != nil {
		panic(err)
	}

	client.DefaultTimeout = timeout
	return netboxRepository{
		client: netbox.New(
			client.NewWithClient(host, basepath, []string{}, httpsClient),
			strfmt.Default,
		),
	}
}

func (nr netboxRepository) GetAdditionalAttributes(ctx context.Context, site string, name string) (facilityID *string, height int64, err error) {
	params := dcim.NewDcimRacksListParams()
	params.Site = &site
	params.Name = &name

	response, err := nr.client.Dcim.DcimRacksList(params, nil)
	if err != nil {
		return
	}

	if response.Payload == nil || response.Payload.Count == nil || *response.Payload.Count != 1 {
		return
	}

	nbRack := response.Payload.Results[0]
	facilityID = nbRack.FacilityID
	height = nbRack.UHeight

	return
}
```

I'll flag you on the internal PR when I have it ready so you can see the code in a bigger context.

**Comment by chrigl** [comment]
The generated code has been generated for package "github.com/davcamer/go-netbox/netbox/..." rather than "github.com/digitalocean/go-netbox/netbox/...". This is what travis is complaining about.

```
[22:33:58] chris@cglaubitz ~/t/g/netbox (0)  (swagger-generated|✔)
> grep -R davcamer ./* | head -n1
./client/virtualization/virtualization_interfaces_list_responses.go:    "github.com/davcamer/go-netbox/netbox/models"
```

**Comment by davcamer** [comment]
Thanks @chrigl. I moved it to the expected place. `licensecheck.sh` is now failing since none of the generated files have the expected license. Does it make sense to include it?

**Comment by simt2** [comment]
Thank you so much for the effort @davcamer , I'm really looking forward to this. I've tried the generated client and ran into an issue regarding marshalling boolean false values. Here is some test code:

```golang
package netbox

import (
	"log"
	"net/http"

	"github.com/digitalocean/go-netbox/netbox/client/dcim"
	"github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

func ListDevices() {
	host := "localhost:8080"
	basepath := "/api"
	transport := client.NewWithClient(host, basepath, []string{}, http.DefaultClient)

	dcimClient := dcim.New(transport, strfmt.Default)
	listParams := dcim.NewDcimDevicesListParams()
	resp, err := dcimClient.DcimDevicesList(listParams, nil)

	if err != nil {
		log.Fatal(err)
	}
	log.Print(resp)
}
```

Calling `resp, err := dcimClient.DcimDevicesList(listParams, nil)` results in the following error:
```
cannot unmarshal number into Go struct field DeviceFace.value of type bool
```

The corresponding `face` value as returned by the api call:
```json
"face": {
  "label": "Front",
  "value": 0
}
```

I don't even know what `face.value` is for. Any takes on that?

**Comment by simt2** [comment]
@davcamer FYI: I have forked your repository, changed `DeviceFace.Value` to an integer enum in the swagger definition and regenerated the client. This works for me. The error probably lies upstream in drf-yasg?

**Comment by davcamer** [comment]
Thanks simt2! I think "face" is one of the values that I wrote custom code to generate swagger for. Any enums are expanded out in to a label and value sub-object like that. I'll have to look in to that.

**Comment by mdlayher** [comment]
Happy to merge this whenever you think it's ready, Dave!

**Comment by davcamer** [comment]
There are a couple of things I haven't looked at yet:
1. How does paging lists work with the client?
1. It should be possible to pass a list of ints as IDs to most objects. However, the client is generating the `InID` field as a `*float64`.

We are using it in prod already to query Racks though.

There could be a long tail of bugs with this swagger approach, since we suddenly have 150k lines of code. (!!) If we could get more people using it though, that would bring the bugs to the surface.

**Comment by chrigl** [comment]
Thanks @davcamer for this huge effort!

> 1. How does paging lists work with the client?

This looks a bit like a pain. At least I was not able to find any kind of interface, shared by all "list-able" types. My quick & dirty code looks like this:
```
        var offset int64

        params := ipam.NewIPAMIPAddressesListParams()
        for {
                params.Offset = &offset
                resp, err := c.IPAM.IPAMIPAddressesList(params, nil)
                if err != nil {
                        log.Fatal(err)
                }

                fmt.Printf("%v\n", resp.Payload.Previous)
                if resp.Payload.Next == nil {
                        break
                }

                urlStr, err := url.Parse(resp.Payload.Next.String())
                if err != nil {
                        log.Fatalf("unexpected %v", err)
                }
                newOffset, ok := urlStr.Query()["offset"]
                if !ok {
                        log.Print("Nothing todo any more")
                        break
                }
                if len(newOffset) > 0 {
                        tmp, err := strconv.ParseInt(newOffset[0], 10, 64)
                        if err != nil {
                                log.Fatal(err)
                        }

                        offset = tmp
                }
        }
```

IMHO, we should split a more generic pager into a separate not-generated package. Maybe there is something shared about those types, that I miss.

> 2. It should be possible to pass a list of ints as IDs to most objects. However, the client is generating the InID field as a *float64.

In the swagger.json the `in__id` fields are defined as `number` rather than array. But I am unsure whether it is worth to edit too much of the json file by hand, to not get too far out of sync with the one, django is going to be created.

**Comment by davcamer** [comment]
I definitely want to make changes in either `netbox` or `drf-yasg` when possible. So far, that has worked. I agree it would make sense to write some non-generated code to make this easier.

**Comment by davcamer** [comment]
I always forget that it isn't possible to define interfaces based on fields. Otherwise, the `Next` and `Previous` field seem like they would be the way to do it.

I looked in to using custom templates with the go-swagger generation. The most obvious thing to me would be to override the model generation and add functions on if the `Next` and `Previous` fields are present. But, go-swagger does not allow overrides for the model templates. 

go-swagger does allow client response templates to be overridden. I think that would make it possible to add methods to response classes such as `DcimDeviceRolesListOK`. They might look something like:
```golang
func (o *DcimDeviceRolesListOK) NextOffset() int {
    urlStr, err := o.Payload.Next.String()
    ... code above from chrigl ...
    return offset
}
```

It would still be up to the user to manipulate the params objects.

**Comment by davcamer** [comment]
I don't think I can take on simplifying the pagination at the moment. Another idea that came to mind was to have a method on the params objects that would generate a new set of params based on a URL. It could be used like:
```golang
dcim.NewParamsTypeFromUrl(response.Next)
```

The function signature would be something like:
```golang
func NewParamsType(url string) ParamsType {
... parse ALL the params out of the url and populate the new struct...
}
```

It is one of the templates that could be overridden in go-swagger, although I think it would be pretty significant work.

**Comment by davcamer** [comment]
I'll merge this tomorrow as long as no one has any other significant feedback.

**Pull request merged**
